spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

cloudflare:
  r2:
    account-id: ${CLOUDFLARE_ACCOUNT_ID}
    access-key: ${CLOUDFLARE_ACCESS_KEY}
    secret-key: ${CLOUDFLARE_SECRET_KEY}
    bucket-name: ${CLOUDFLARE_BUCKET_NAME}
    endpoint: ${CLOUDFLARE_ENDPOINT}

logging:
  level:
    root: INFO
    com.example.auction_market: DEBUG   # 우리 패키지 로그 자세히

